name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          pip install poetry==1.7.1
          poetry config virtualenvs.create false
          poetry install --with dev,test

      - name: Run Unit Tests
        run: pytest tests -m 'not integration_test'

      - name: Run Integration Tests
        run: pytest tests -m 'integration_test'
        env:
          AF_KLM_API_KEY: ${{ secrets.AF_KLM_API_KEY }}
          AF_KLM_API_SECRET: ${{ secrets.AF_KLM_API_SECRET }}
          LOG_LEVEL: INFO